language: objective-c
branches:
  only:
  - master
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=OVHAPIWrapper.xcworkspace
  - IOS_SDK=iphonesimulator9.2
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator9.1
  - WATCHOS_SDK=watchsimulator2.1
  - IOS_FRAMEWORK_SCHEME="OVHAPIWrapper iOS"
  - OSX_FRAMEWORK_SCHEME="OVHAPIWrapper OSX"
  - TVOS_FRAMEWORK_SCHEME="OVHAPIWrapper tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="OVHAPIWrapper watchOS"
  - IOS_EXAMPLE_SCHEME="OVHAPIWrapper-Example-iOS"
  matrix:
    - DESTINATION="OS=8.0,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=9.1,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     EXAMPLE_SCHEME=""                    RUN_TESTS="YES" BUILD_EXAMPLE="NO"
    - DESTINATION="OS=9.1,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    EXAMPLE_SCHEME=""                    RUN_TESTS="YES" BUILD_EXAMPLE="NO"
    - DESTINATION="OS=2.1,name=Apple Watch - 38mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" EXAMPLE_SCHEME=""                    RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Example in Release if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
